name: Fetch and Pull Updates

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
    # https://github.com/orgs/community/discussions/8726

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Fetch and Merge from Origin
        run: |
          git fetch origin
          git merge origin/$(git rev-parse --abbrev-ref HEAD) --no-edit
